syntax = "proto3";

package repository;

option go_package = "github.com/dositadi/cheffery/repository";

import "google/protobuf/timestamp.proto";
import "google/protobuf/duration.proto";

message CreateUserRequest {
    string name = 1;
    string email = 2;
    bytes passwordHash = 3;
    string reqID = 4;
}

message CreateUserResponse {
    string id = 1;
    google.protobuf.Timestamp createdAt = 2;
}

message DeleteUserRequest {
    string id = 1;
    string reqID = 2;
}

message DeleteUserResponse {}

message GetUserRequest {
    string reqID = 1;
    string userID = 2;
}

message GetUserResponse {
    string id = 1;
    string name = 2;
    string email = 3;
    int32 version = 5;
    google.protobuf.Timestamp createdAt = 6;
    google.protobuf.Timestamp updatedAt = 7;
}

message UpdateUserRequest {
    string name = 1;
    string email = 2;
    string newPassword = 3;
    string oldPassword = 4;
    string id = 5;
    string reqID = 6;
}

message UpdateUserResponse {
    bool datachanged = 1;
    repeated string fields = 2;
    google.protobuf.Timestamp timestamp = 3; 
}

message DBHealthRequest {
    string reqID = 1; 
}

message DBHealthResponse {
    string status = 1;
    DBHealth dbHealth = 2;
    google.protobuf.Duration latency = 3;
    google.protobuf.Timestamp timestamp = 4;
    string reqID = 5;
}

message DBHealth {
    bool connected = 1;
    bool poolHealthy = 2;
    int32 totalConns = 3;
    int32 idleConns = 4;
    int32 acquiredConns = 5;
    int32 acquiredCount = 6;
    int32 createdCount = 7;
    int32 releasedCount = 8;
    int32 destroyedCount = 9;
    string message = 10; 
}

service Repository {
    rpc CreateUser(CreateUserRequest) returns (CreateUserResponse);
    rpc GetUser (GetUserRequest) returns (GetUserResponse);
    rpc UpdateUser (UpdateUserRequest) returns (UpdateUserResponse);
    rpc DeleteUser (DeleteUserRequest) returns (DeleteUserResponse);
    rpc DBHealth(DBHealthRequest) returns (DBHealthResponse);
}