// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           uuid.UUID
	Name         string
	Email        string
	PasswordHash []byte
	Createdat    time.Time
	Updatedat    time.Time
	Deletedat    pgtype.Timestamptz
}
