// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    name, email, password_hash
) VALUES (
    $1, $2, $3
)
RETURNING id, created_at
`

type CreateUserParams struct {
	Name         string
	Email        string
	PasswordHash []byte
}

type CreateUserRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Email, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, name, email, password_hash, created_at, updated_at, version, deletedat FROM users
WHERE id = $1 AND deletedAt IS NULL
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.Deletedat,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET name = $1, email = $2, password_hash = $3, version = version + 1, updated_at = NOW()
WHERE id = $4 AND version = $5
`

type UpdateUserParams struct {
	Name         string
	Email        string
	PasswordHash []byte
	ID           uuid.UUID
	Version      int32
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.ID,
		arg.Version,
	)
	return err
}
