// The syntax declaration must be the first in the proto file

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: protoc/auth/auth.proto

// The package name helps avoid naming conflicts between proto definitions.

package gen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Issuer_GenerateTokenPair_FullMethodName    = "/auth.Issuer/GenerateTokenPair"
	Issuer_ValidateAccessToken_FullMethodName  = "/auth.Issuer/ValidateAccessToken"
	Issuer_ValidateRefreshToken_FullMethodName = "/auth.Issuer/ValidateRefreshToken"
	Issuer_Logout_FullMethodName               = "/auth.Issuer/Logout"
	Issuer_RotateRefreshToken_FullMethodName   = "/auth.Issuer/RotateRefreshToken"
)

// IssuerClient is the client API for Issuer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Issuer service is in charge of handling all the various request
type IssuerClient interface {
	GenerateTokenPair(ctx context.Context, in *GenerateTokenPairRequest, opts ...grpc.CallOption) (*GenerateTokenPairResponse, error)
	ValidateAccessToken(ctx context.Context, in *ValidateAccessTokenRequest, opts ...grpc.CallOption) (*ValidateAccessTokenResponse, error)
	ValidateRefreshToken(ctx context.Context, in *ValidateRefreshTokenRequest, opts ...grpc.CallOption) (*ValidateRefreshTokenResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	RotateRefreshToken(ctx context.Context, in *RotateRefreshTokenRequest, opts ...grpc.CallOption) (*RotateRefreshTokenResponse, error)
}

type issuerClient struct {
	cc grpc.ClientConnInterface
}

func NewIssuerClient(cc grpc.ClientConnInterface) IssuerClient {
	return &issuerClient{cc}
}

func (c *issuerClient) GenerateTokenPair(ctx context.Context, in *GenerateTokenPairRequest, opts ...grpc.CallOption) (*GenerateTokenPairResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateTokenPairResponse)
	err := c.cc.Invoke(ctx, Issuer_GenerateTokenPair_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issuerClient) ValidateAccessToken(ctx context.Context, in *ValidateAccessTokenRequest, opts ...grpc.CallOption) (*ValidateAccessTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateAccessTokenResponse)
	err := c.cc.Invoke(ctx, Issuer_ValidateAccessToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issuerClient) ValidateRefreshToken(ctx context.Context, in *ValidateRefreshTokenRequest, opts ...grpc.CallOption) (*ValidateRefreshTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateRefreshTokenResponse)
	err := c.cc.Invoke(ctx, Issuer_ValidateRefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issuerClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, Issuer_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issuerClient) RotateRefreshToken(ctx context.Context, in *RotateRefreshTokenRequest, opts ...grpc.CallOption) (*RotateRefreshTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateRefreshTokenResponse)
	err := c.cc.Invoke(ctx, Issuer_RotateRefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IssuerServer is the server API for Issuer service.
// All implementations must embed UnimplementedIssuerServer
// for forward compatibility.
//
// Issuer service is in charge of handling all the various request
type IssuerServer interface {
	GenerateTokenPair(context.Context, *GenerateTokenPairRequest) (*GenerateTokenPairResponse, error)
	ValidateAccessToken(context.Context, *ValidateAccessTokenRequest) (*ValidateAccessTokenResponse, error)
	ValidateRefreshToken(context.Context, *ValidateRefreshTokenRequest) (*ValidateRefreshTokenResponse, error)
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	RotateRefreshToken(context.Context, *RotateRefreshTokenRequest) (*RotateRefreshTokenResponse, error)
	mustEmbedUnimplementedIssuerServer()
}

// UnimplementedIssuerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIssuerServer struct{}

func (UnimplementedIssuerServer) GenerateTokenPair(context.Context, *GenerateTokenPairRequest) (*GenerateTokenPairResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateTokenPair not implemented")
}
func (UnimplementedIssuerServer) ValidateAccessToken(context.Context, *ValidateAccessTokenRequest) (*ValidateAccessTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateAccessToken not implemented")
}
func (UnimplementedIssuerServer) ValidateRefreshToken(context.Context, *ValidateRefreshTokenRequest) (*ValidateRefreshTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateRefreshToken not implemented")
}
func (UnimplementedIssuerServer) Logout(context.Context, *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedIssuerServer) RotateRefreshToken(context.Context, *RotateRefreshTokenRequest) (*RotateRefreshTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateRefreshToken not implemented")
}
func (UnimplementedIssuerServer) mustEmbedUnimplementedIssuerServer() {}
func (UnimplementedIssuerServer) testEmbeddedByValue()                {}

// UnsafeIssuerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IssuerServer will
// result in compilation errors.
type UnsafeIssuerServer interface {
	mustEmbedUnimplementedIssuerServer()
}

func RegisterIssuerServer(s grpc.ServiceRegistrar, srv IssuerServer) {
	// If the following call panics, it indicates UnimplementedIssuerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Issuer_ServiceDesc, srv)
}

func _Issuer_GenerateTokenPair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateTokenPairRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssuerServer).GenerateTokenPair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Issuer_GenerateTokenPair_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssuerServer).GenerateTokenPair(ctx, req.(*GenerateTokenPairRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Issuer_ValidateAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateAccessTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssuerServer).ValidateAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Issuer_ValidateAccessToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssuerServer).ValidateAccessToken(ctx, req.(*ValidateAccessTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Issuer_ValidateRefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssuerServer).ValidateRefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Issuer_ValidateRefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssuerServer).ValidateRefreshToken(ctx, req.(*ValidateRefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Issuer_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssuerServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Issuer_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssuerServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Issuer_RotateRefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateRefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssuerServer).RotateRefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Issuer_RotateRefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssuerServer).RotateRefreshToken(ctx, req.(*RotateRefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Issuer_ServiceDesc is the grpc.ServiceDesc for Issuer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Issuer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.Issuer",
	HandlerType: (*IssuerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateTokenPair",
			Handler:    _Issuer_GenerateTokenPair_Handler,
		},
		{
			MethodName: "ValidateAccessToken",
			Handler:    _Issuer_ValidateAccessToken_Handler,
		},
		{
			MethodName: "ValidateRefreshToken",
			Handler:    _Issuer_ValidateRefreshToken_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _Issuer_Logout_Handler,
		},
		{
			MethodName: "RotateRefreshToken",
			Handler:    _Issuer_RotateRefreshToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protoc/auth/auth.proto",
}
